export const ChampionsRadius = [
    { name: "Aatrox", size: 65 },
    { name: "Ahri", size: 65 },
    { name: "Akali", size: 65 },
    { name: "Akshan", size: 65 },
    { name: "Alistar", size: 80 },
    { name: "Amumu", size: 55 },
    { name: "Anivia", size: 65 },
    { name: "Annie", size: 55 },
    { name: "Aphelios", size: 65 },
    { name: "Ashe", size: 65 },
    { name: "Aurelion Sol", size: 65 },
    { name: "Azir", size: 65 },
    { name: "Bard", size: 80 },
    { name: "Bel'Veth", size: 65 },
    { name: "Blitzcrank", size: 80 },
    { name: "Brand", size: 65 },
    { name: "Braum", size: 80 },
    { name: "Caitlyn", size: 65 },
    { name: "Camille", size: 65 },
    { name: "Cassiopeia", size: 65 },
    { name: "Cho'Gath", size: 80 },
    { name: "Corki", size: 65 },
    { name: "Darius", size: 80 },
    { name: "Diana", size: 65 },
    { name: "Dr.Mundo", size: 80 },
    { name: "Draven", size: 65 },
    { name: "Ekko", size: 65 },
    { name: "Elise", size: 65 },
    { name: "Evelynn", size: 65 },
    { name: "Ezreal", size: 65 },
    { name: "Fiddlesticks", size: 65 },
    { name: "Fiora", size: 65 },
    { name: "Fizz", size: 55 },
    { name: "Galio", size: 80 },
    { name: "Gangplank", size: 65 },
    { name: "Garen", size: 65 },
    { name: "Gnar", size: 65 },
    { name: "Gragas", size: 80 },
    { name: "Graves", size: 65 },
    { name: "Gwen", size: 65 },
    { name: "Hecarim", size: 80 },
    { name: "Heimerdinger", size: 55 },
    { name: "Illaoi", size: 65 },
    { name: "Irelia", size: 65 },
    { name: "Ivern", size: 70 },
    { name: "Janna", size: 65 },
    { name: "Jarvan IV", size: 65 },
    { name: "Jax", size: 65 },
    { name: "Jayce", size: 65 },
    { name: "Jhin", size: 65 },
    { name: "Jinx", size: 65 },
    { name: "Kai'Sa", size: 65 },
    { name: "Kalista", size: 65 },
    { name: "Karma", size: 65 },
    { name: "Karthus", size: 65 },
    { name: "Kassadin", size: 65 },
    { name: "Katarina", size: 65 },
    { name: "Kayle", size: 65 },
    { name: "Kayn", size: 65 },
    { name: "Kennen", size: 55 },
    { name: "Kha'Zix", size: 65 },
    { name: "Kindred", size: 65 },
    { name: "Kled", size: 65 },
    { name: "KogMaw", size: 65 },
    { name: "LeBlanc", size: 65 },
    { name: "Lee Sin", size: 65 },
    { name: "Leona", size: 65 },
    { name: "Lillia", size: 65 },
    { name: "Lissandra", size: 65 },
    { name: "Lucian", size: 65 },
    { name: "Lulu", size: 65 },
    { name: "Lux", size: 65 },
    { name: "Malphite", size: 80 },
    { name: "Malzahar", size: 65 },
    { name: "Maokai", size: 80 },
    { name: "Master Yi", size: 65 },
    { name: "Mega Gnar", size: 65 },
    { name: "MissFortune", size: 65 },
    { name: "Mordekaiser", size: 80 },
    { name: "Morgana", size: 65 },
    { name: "Nami", size: 65 },
    { name: "Nasus", size: 80 },
    { name: "Nautilus", size: 80 },
    { name: "Neeko", size: 65 },
    { name: "Nidalee", size: 65 },
    { name: "Nilah", size: 65 },
    { name: "Nocturne", size: 65 },
    { name: "Nunu", size: 65 },
    { name: "Olaf", size: 65 },
    { name: "Orianna", size: 65 },
    { name: "Ornn", size: 80 },
    { name: "Pantheon", size: 65 },
    { name: "Poppy", size: 55 },
    { name: "Pyke", size: 65 },
    { name: "Qiyana", size: 65 },
    { name: "Quinn", size: 65 },
    { name: "Rakan", size: 65 },
    { name: "Rammus", size: 65 },
    { name: "Rek'Sai", size: 65 },
    { name: "Rell", size: 65 },
    { name: "Renata Glasc", size: 65 },
    { name: "Renekton", size: 80 },
    { name: "Rengar", size: 65 },
    { name: "Riven", size: 65 },
    { name: "Rumble", size: 80 },
    { name: "Ryze", size: 65 },
    { name: "Samira", size: 65 },
    { name: "Sejuani", size: 80 },
    { name: "Senna", size: 65 },
    { name: "Seraphine", size: 65 },
    { name: "Sett", size: 65 },
    { name: "Shaco", size: 65 },
    { name: "Shen", size: 65 },
    { name: "Shyvana", size: 65 },
    { name: "Singed", size: 65 },
    { name: "Sion", size: 80 },
    { name: "Sivir", size: 65 },
    { name: "Skarner", size: 80 },
    { name: "Sona", size: 65 },
    { name: "Soraka", size: 65 },
    { name: "Swain", size: 65 },
    { name: "Sylas", size: 65 },
    { name: "Syndra", size: 65 },
    { name: "Tahm Kench", size: 80 },
    { name: "Taliyah", size: 65 },
    { name: "Talon", size: 65 },
    { name: "Taric", size: 65 },
    { name: "Teemo", size: 55 },
    { name: "Thresh", size: 65 },
    { name: "Tristana", size: 55 },
    { name: "Trundle", size: 65 },
    { name: "Tryndamere", size: 65 },
    { name: "Twisted Fate", size: 65 },
    { name: "Twitch", size: 65 },
    { name: "Udyr", size: 65 },
    { name: "Urgot", size: 80 },
    { name: "Varus", size: 65 },
    { name: "Vayne", size: 65 },
    { name: "Veigar", size: 55 },
    { name: "Vel'Koz", size: 65 },
    { name: "Vex", size: 65 },
    { name: "Vi", size: 65 },
    { name: "Viego", size: 65 },
    { name: "Viktor", size: 65 },
    { name: "Vladimir", size: 65 },
    { name: "Volibear", size: 80 },
    { name: "Warwick", size: 55 },
    { name: "Wukong", size: 65 },
    { name: "Xayah", size: 65 },
    { name: "Xerath", size: 65 },
    { name: "Xin Zhao", size: 65 },
    { name: "Yasuo", size: 65 },
    { name: "Yone", size: 65 },
    { name: "Yorick", size: 80 },
    { name: "Yuumi", size: 65 },
    { name: "Zac", size: 80 },
    { name: "Zed", size: 65 },
    { name: "Zeri", size: 65 },
    { name: "Ziggs", size: 55 },
    { name: "Zilean", size: 65 },
    { name: "Zoe", size: 65 },
    { name: "Zyra", size: 65 }
];


export function getChampionRadius(name: string) {
    const target = ChampionsRadius.find(e => e.name == name);
    if (target) return target;

    for (const entry of ChampionsRadius) {
        const name = entry.name;
        if (name.toLowerCase().replace(/ /g, '') == name) return entry;
    }

    if (!name.startsWith('PracticeTool')) {
        console.log('CANNOT FIND', name, 'RADIUS');
    }
    return { name, size: 50 }
}